export const AJAX_BEGIN_CALL = 'AJAX_BEGIN_CALL';
export const AJAX_END_CALL = 'AJAX_END_CALL';

export const LOAD_QUESTIONS_AND_ANSWERS_SUCCESS = 'LOAD_QUESTIONS_AND_ANSWERS_SUCCESS';
export const CLEAR_TASK = 'CLEAR_TASK';


export const LOAD_PROVIDERS_SUCCESS = 'LOAD_PROVIDERS_SUCCESS';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const USER_FINISHED_PLAYING = 'USER_FINISHED_PLAYING';

export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS';
export const DELETE_RESULTS_SUCCESS = 'DELETE_RESULTS_SUCCESS';
